### ISSUE TITLE
Developers: Requested Rippers up-for-grabs (meta-issue)

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#510]
# Note: assume all links are NSFW

If you would like to develop a ripper which has been requested, please open an issue (to function as a work item) indicating that you've claimed a ripper and you're working on an implementation. Please link back to this issue (and #502 as an FYI) so that GitHub makes a link to the issue (work item) appear in this thread and #502.

~~I'm locking this conversation to ensure requests and general comments stay on #502.~~ (It looks like link-backs won't appear on a locked issue, so I won't be able to lock this issue.)

To keep this issue focused, **I will delete requests and non-dev-related comments (please use #502 for these).**

Below is a list of rippers and functionality requested via #502 and #8 (this list is a work in progress -- I'm posting a thumbs-up reaction on any requests I have added to this list). Please assume all links are NSFW.

### High priority (existing rippers: broken or missing functionality)

* [ ] Fix `DeviantART`: #272 #112 #63
* [ ] `DeviantART` favorites galleries e.g. http://philosophyfetish.deviantart.com/favourites/ ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-296430431))
* [ ] `DeviantART` gallery recursive ripping (#550)
* [ ] `Tumblr` liked by {User}: https://www.tumblr.com/liked/by/hacky-gif ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-296959726))
* [ ] `eroshare` User Pages (#465) and direct links (#526)

### Everything else:

* [ ] `PurplePort`: https://purpleport.com/ e.g. https://purpleport.com/portfolio/bluethealienteafairy/ ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-292073508))
* [ ] `CFake`: http://cfake.com/ e.g. http://cfake.com/picture/Olivia-Munn/969 ([Request](https://github.com/4pr0n/ripme/issues/8#issuecomment-163521926), [Comment](https://github.com/4pr0n/ripme/issues/8#issuecomment-286962054), [Comment](https://github.com/4pr0n/ripme/issues/502#issuecomment-292816317))
* [ ] `VSCO`: http://www.vsco.co e.g. https://vsco.co/lukept/images/1 ([Request](https://github.com/4pr0n/ripme/issues/8#issuecomment-284197479), [Comment](https://github.com/4pr0n/ripme/issues/8#issuecomment-290597282), [Comment](https://github.com/4pr0n/ripme/issues/502#issuecomment-292129058))
* [ ] `zenfolio` https://en.zenfolio.com ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-293748612))
* [ ] `smugmug` https://www.smugmug.com/ ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-293748612))
* [ ] `sex.com`: (Request: https://github.com/4pr0n/ripme/issues/274)

### Pending sites + examples (from #8)

- `getgonewild` - http://www.getgonewild.com/profile/rollmeup
- `blogspot` - http://marcherryfashion.blogspot.com/
- `pixiv` - http://www.pixiv.net/member.php?id=2136123
- `facebook` - https://www.facebook.com/EmanueleFerrariPhotographer/photos_stream
- `pinterest` - http://www.pinterest.com/
- `lookbook` - http://lookbook.nu/mayowo
- `4shared` - http://www.4shared.com/folder/pTUpT6wG/Heather.html
- `behance` - https://www.behance.net/HS-nj
- `dribbble` - https://dribbble.com/studioMUTI
- `fetlife` - https://fetlife.com/users/2089769
- `diverxity` - http://www.diverxity.com/users/953
- `studio-g` - http://studio-g.tistory.com/535
- `fg-site` - http://www.fg-site.net/members/umeume/
- `gelbooru` - http://gelbooru.com/index.php?page=post&s=list&tags=futa
- `thefappening.sexy` - http://thefappening.sexy/albums/index.php?/category/126
- `ipernity` - http://www.ipernity.com/doc/kimcums/album/676241
- `punterplanet` - http://guide.punterplanet.com/escorts/featured/frontpage/amber-green_200.html
- `rule34` - rule34.paheal.net
- `photoblog.pl` - http://www.photoblog.pl/colordust/170020651/typical-girl.html
- `megamodels.pl` - http://www.megamodels.pl/a-ya
- `maxmodels.pl` - http://www.maxmodels.pl/modelka-agnes-z-garbledville.html
- `flog.pl` - http://www.flog.pl/szukaj/akt

### Enhancement requests (list from #8):

- `flickr` - login support (see #32)
- `vk` - Video ripper rename files (https://github.com/4pr0n/ripme/issues/8#issuecomment-41349715)
- `twitter` - Search ripping (https://github.com/4pr0n/ripme/issues/8#issuecomment-41471274)
- `gifyo` - Don't skip some images
- `*chan rippers` - Handle external links (vocaroo), store comments
- `tumblr` - Rip by date (`/archive/year/month`) (https://github.com/4pr0n/ripme/issues/8#issuecomment-41395317)

### Acknowledged but defunct requests:

* ~~kinkyshare.com (now redirects to sex.com, old content seems to be gone) ([Request](https://github.com/4pr0n/ripme/issues/8#issuecomment-40618854))~~
* ~~`artician` - http://zionenciel.artician.com/~~

**Comment by Wiiplay123** [comment]
I've made a working implementation and submitted a pull request, but I think it could be done better when someone has the time if they use org.json. Should I still make an issue even if I'm not likely to be able to  continue to devote much time to it?

**Comment by metaprime** [comment]
@Wiiplay123 I think there are plenty of issues already open to track the various DeviantArt problems. If you have a patch, please open a PR. If you don't think it's good enough, it won't work, or whatever, please make that clear in the pull request description. Maybe someone else will be able to pick up the work.

**Comment by Wiiplay123** [comment]
I opened a PR, turns out the modified ripper is even better than the original ripper, since it accounts for those annoying download redirects that redirect you back to the gallery page.
